### ISSUE TITLE
Issue with pushing new branches up stream

### ISSUE THREAD

**Issue by Mozmani** [mieweb/mie-dev-challenge#1]
Hey there, 

I hope all is well on your end!

I was trying to push up my development branch to the remote repository so that I could access it on my my other desktop.  The issue is that I do not actually have access to creating sub branches on this repository.  If possible I would like to have access to creating branches on the remote repository.

-Mark

**Comment by george-jones** [comment]
Hi Mark, the issue with giving that access would be that your branch would be visible to others taking the challenge, and we'd like to avoid that, so we give read-only access to people taking the challenge. For your scenario, I'm thinking you could make your own private repo on github and then on your desktop edit the .git/config to have your [remote "origin"] url be that of your private repo instead of the one for this project. Do you think that would work?

**Comment by Mozmani** [comment]
Ah yes that should work just fine and thank you for the quick response! Just to verify, when I am completed do yo want it as a pull request here?

**Comment by george-jones** [comment]
You could either make me a collaborator on your private repo (preferred) or bundle up your source files in a zip file and email it to Lisa. Thanks for your patience with this process - we've recently changed to this new format for our challenge and probably need to make some of these steps clearer in the readme file.

**Comment by Mozmani** [comment]
Understood, I have it all set up on my own private repository (Last night I made the mistake of not having the origin call after set-url. . . haha). As soon as it is done I shall invite you as a collaborator! Thank you for the quick responses!
